on:
  push:
    branches:
      - next

jobs:
  website:
    name: Build and deploy website to preview-gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: preview-gh-pages
          folder: out